# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jonathan Dorairaj
title: TODO
email: jonathan.dorairaj@gmail.com
website: www.github.com/jonathandorairaj

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  jonathandorairaj
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: jonathan-dorairaj-7b443b164
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: itsgoingto.be
  icon: fas fa-globe
  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Brett and I'm a senior network system administrator. As well as administrating systems I also have experience making software and web apps. I have worked at a number of companies gaining teamwork and leadership skills.

  I am most skilled in: <mark>AWS</mark> and <mark>Eating Pizza</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Wipro Limited
        link: wipro.com
        # link_text: boringcompany.com
        sub_title: Senior Information Security Analyst
        caption: May 2021 - Jan 2022
        quote: >
          Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            - Created a dashboard in Demisto displaying all important metrics increasing productivity and reducing time to resolution across the entire team by 10-15\%}
            - Received 3 awards for individual contributions and investigation quality.
            - Investigated 200+ network attacks and analyzed malicious files, leading to the quarantine and sanitization of endpoints.
            - Troubleshot Cortex SOAR incidents, enhancing automated playbook response times by 30%
            - Resolved over 300 escalated tickets with comprehensive evidence and analysis, supporting successful case closures.
            - Diagnosed and remedied SOC issues, reducing resolution time and preventing logjams.
            - Investigated and resolved over 1000+ phishing incidents, Antivirus alerts, suspicious processes, and PowerShell scripts.
            - Improved Operation Procedures by sharing alternative investigative methods, and addressed inefficiencies.
            

      - layout: left
        title: Wipro Limited
        link: wipro.com
        subtitle : Information Security Analyst
        caption: Jan 2019 - April 2021
        quote: >
          Something here
        description: |
            - Investigated and resolved over 7000+ alerts, events, and incidents.
            - Ranked in the top 10% for productivity, delivering the highest performance metrics in the team.
            - Received multiple monthly awards for high performance and productivity.
            - Identified and blocked over 200+ Indicators of Compromise.
            - Triaged incoming alerts based on severity.
            - Monitored network for alerts and DDoS attacks with 100% SLA time.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Linköping University
        caption: 2022 - 2024
        sub_title: Master's in Statistics and Machine Learning
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification
  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      This is where you can write a little more about yourself. You could title this section **Interests** and include some of your other interests.

      Or you could title it **Skills** and write a bit more about things that make you more desirable, like *leadership* or *teamwork*

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
 theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
